/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [
    'home',
    {
      type: 'category',
      label: 'Android SDK',
      link: {
        type: 'doc',
        id: 'index/android',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'android',
        },
      ],
    },
    {
      type: 'category',
      label: 'iOS SDK',
      link: {
        type: 'doc',
        id: 'index/ios',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ios'
        },
      ],
    },
    {
      type: 'category',
      label: 'Web JS SDK',
      link: {
        type: 'doc',
        id: 'index/webjs',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'webjs'
        },
      ],
    },
    {
      type: 'category',
      label: '小程序 SDK',
      link: {
        type: 'doc',
        id: 'index/miniprogram',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'miniprogram'
        },
      ],
    },
    {
      type: 'category',
      label: '多平台 SDK',
      link: {
        type: 'doc',
        id: 'index/framework',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'framework'
        },
      ],
    },
    {
      type: 'category',
      label: 'GioKit 性能插件',
      link: {
        type: 'doc',
        id: 'index/giokit',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'giokit'
        },
      ],
    },
    'measurement',
  ],

  serverSidebar: [{type: 'autogenerated', dirName: 'server'}],
  questionSidebar: [{type: 'autogenerated', dirName: 'question'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
